const productosData = [
    {
      id: 1,
      nombre: "Smartphone XYZ",
      categoria: 1,
      precio: 301.500,
      descripcion: "",
      caracteristicas: ["Pantalla OLED", "Cámara 108MP", "Batería 5000mAh", "5G"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_958027-MLU74181419815_012024-O.webp",
      calificacion: 4.5,
      destacado: true,
      purchases: 150
    },
    {
      id: 2,
      nombre: "pc gamer",
      categoria: 1,
      precio: "1.023.500",
      descripcion: "Marca: AMD, Modelo: RYZEN 7 5700G, Tipo de procesador: RYZEN 7 5700G, Tamaño del disco duro: 1 TB, Marca del procesador: AMD, Línea del procesador: Ryzen 7, Modelo del procesador: 5700G",
      caracteristicas: ["Procesador i7", "16GB RAM", "512GB SSD", "Pantalla 4K"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_643509-MLA75371068291_032024-O.webp",
      calificacion: 4.8,
      destacado: true,
      purchases: 120
    },
    {
      id: 3,
      nombre: "Notebook Asus",
      categoria: 2,
      precio: 718.799,
      descripcion: "Notebook Asus X515ea-ej3968 Fhd I3 8gb/256gb Ssd Anti Glare Color Gris",
      caracteristicas: ["Con pantalla táctil: No", "Resolución de la pantalla: FHD 1920 x 1080", "Procesador: Intel Core i3 1115G4", "Sistema operativo: FreeDOS", "Capacidad de disco SSD: 256 GB", "Memoria RAM: 8 GB", "Conexión wifi y bluetooth.", "Cuenta con 4 puertos USB y puerto HDMI.", "Modo de sonido Mono."],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_695271-MLU75875689417_042024-O.webp",
      calificacion: 4.2,
      destacado: false,
      purchases: 200
    },
    {
      id: 50,
      nombre: "PC gamer",
      categoria: 1,
      precio: 794.970,
      descripcion: "Pc Gamer Amd Ryzen 7 5700g 32gb Ssd 1tb",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_989280-MLA79345152351_092024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 501,
      nombre: "Reloj Inteligente Pro",
      categoria: 1,
      precio: 314.999,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_770416-MLA74084789641_012024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 502,
      nombre: "ZTE V50",
      categoria: 1,
      precio: 259.999,
      descripcion: "ZTE V50 Design 256 GB negro 6 GB RAM.",
      caracteristicas: ["Pantalla IPS de 6.6", " 3 cámaras traseras de 50Mpx/2Mpx/2Mpx", "Batería de 5000mAh.", "Cámara delantera de 8Mp","Memoria interna de 256GB."],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_858914-MLA76441935671_052024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 503,
      nombre: "Pc Gamer ",
      categoria: 1,
      precio: 
      407.205,
      descripcion: "Pc Gamer Amd Ryzen 5 5600g 16gb A520m Ssd 240gb",
      caracteristicas: [
        "AMD",
        "Ryzen 5",
        "Ryzen 5 5600GT",
        "240 GB",
        "16 GB",
        ],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_879438-MLA75890710977_042024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 504,
      nombre: "Reloj Inteligente Pro",
      categoria: 1,
      precio: 299.99,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_919538-MLA69552280767_052023-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 505,
      nombre: "Reloj Inteligente Pro",
      categoria: 1,
      precio: 299.99,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 506,
      nombre: "Reloj Inteligente Pro",
      categoria: 1,
      precio: 299.99,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 507,
      nombre: "Reloj Inteligente Pro",
      categoria: 2,
      precio: 299.99,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 508,
      nombre: "Reloj Inteligente Pro",
      categoria: 3,
      precio: 299.99,
      descripcion: "Reloj inteligente con múltiples funciones de salud y fitness.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 180
    },
    {
      id: 519,
      nombre: "Reloj Inteligente Básico",
      categoria: 1,
      precio: 199.99,
      descripcion: "Reloj inteligente con funciones básicas.",
      caracteristicas: ["Monitor cardíaco", "GPS integrado", "Resistente al agua", "Batería de larga duración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 50
    },
    {
      id: 520,
      nombre: "Cámara de Seguridad",
      categoria: 1,
      precio: 89.99,
      descripcion: "Cámara de seguridad para interiores y exteriores.",
      caracteristicas: ["Visión nocturna", "Conexión Wi-Fi", "Detección de movimiento", "Batería recargable"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 30
    },
    {
      id: 521,
      nombre: "Tablet 10\"",
      categoria: 1,
      precio: 299.99,
      descripcion: "Tablet de 10 pulgadas con pantalla HD.",
      caracteristicas: ["Almacenamiento: 64GB", "Cámara frontal", "Conexión Bluetooth", "Batería de 12 horas"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.7,
      destacado: true,
      purchases: 70
    },
    {
      id: 522,
      nombre: "Cargador Solar",
      categoria: 1,
      precio: 49.99,
      descripcion: "Cargador solar portátil para dispositivos móviles.",
      caracteristicas: ["Capacidad: 10000mAh", "Resistente al agua", "Compatible con todos los smartphones"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: false,
      purchases: 100
    },
    {
      id: 523,
      nombre: "Cafetera Eléctrica",
      categoria: 3,
      precio: 79.99,
      descripcion: "Cafetera eléctrica con función de programación.",
      caracteristicas: ["Capacidad: 12 tazas", "Placa caliente", "Filtro reutilizable"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 524,
      nombre: "Silla de Oficina",
      categoria: 3,
      precio: 149.99,
      descripcion: "Silla ergonómica para oficina con soporte lumbar.",
      caracteristicas: ["Ajustable en altura", "Ruedas giratorias", "Material: malla"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 40
    },
    {
      id: 525,
      nombre: "Juego de Sábanas",
      categoria: 3,
      precio: 39.99,
      descripcion: "Juego de sábanas de microfibra suave y duradero.",
      caracteristicas: ["Tamaños: individual, matrimonial", "Colores: varios", "Fácil de lavar"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: false,
      purchases: 80
    },
    {
      id: 526,
      nombre: "Botella de Agua",
      categoria: 4,
      precio: 19.99,
      descripcion: "Botella de agua reutilizable de acero inoxidable.",
      caracteristicas: ["Capacidad: 500ml", "Aislante", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 150
    },
    {
      id: 527,
      nombre: "Mancuernas Ajustables",
      categoria: 4,
      precio: 59.99,
      descripcion: "Mancuernas ajustables para entrenamiento en casa.",
      caracteristicas: ["Peso ajustable", "Material: hierro", "Fácil de almacenar"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 90
    },
    {
      id: 528,
      nombre: "Pelota de Yoga",
      categoria: 4,
      precio: 29.99,
      descripcion: "Pelota de yoga para ejercicios de equilibrio.",
      caracteristicas: ["Diámetro: 65cm", "Material: PVC", "Incluye bomba"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 110
    },
    {
      id: 529,
      nombre: "Libro de Autoayuda",
      categoria: 5,
      precio: 14.99,
      descripcion: "Libro de autoayuda para mejorar la productividad.",
      caracteristicas: ["Autor: Jane Doe", "Páginas: 250", "Formato: tapa blanda"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 200
    },
    {
      id: 530,
      nombre: "Guía de Viajes",
      categoria: 5,
      precio: 19.99,
      descripcion: "Guía de viajes con recomendaciones de destinos.",
      caracteristicas: ["Incluye mapas", "Consejos de viaje", "Formato: tapa dura"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 150
    },
    {
      id: 531,
      nombre: "Novela Romántica",
      categoria: 5,
      precio: 12.99,
      descripcion: "Novela romántica que explora el amor y la amistad.",
      caracteristicas: ["Autor: Emily Smith", "Páginas: 300", "Formato: tapa blanda"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 180
    },
    {
      id: 532,
      nombre: "Manual de Cocina Vegana",
      categoria: 5,
      precio: 24.99,
      descripcion: "Recetas veganas fáciles y deliciosas.",
      caracteristicas: ["Recetas: 100", "Formato: tapa blanda", "Incluye fotos"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 90
    },
    {
      id: 533,
      nombre: "Diccionario Inglés-Español",
      categoria: 5,
      precio: 29.99,
      descripcion: "Diccionario completo para estudiantes de idiomas.",
      caracteristicas: ["Páginas: 500", "Formato: tapa dura", "Incluye ejemplos"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 120
    },
    {
      id: 534,
      nombre: "Cuaderno de Notas",
      categoria: 5,
      precio: 9.99,
      descripcion: "Cuaderno de notas con hojas rayadas.",
      caracteristicas: ["Páginas: 200", "Tamaño: A5", "Cubierta: dura"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 200
    },
    {
      id: 535,
      nombre: "Agenda 2023",
      categoria: 5,
      precio: 19.99,
      descripcion: "Agenda para organizar tus actividades diarias.",
      caracteristicas: ["Formato: A5", "Páginas: 365", "Diseño: elegante"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 150
    },
    {
      id: 536,
      nombre: "Rompecabezas 1000 Piezas",
      categoria: 5,
      precio: 29.99,
      descripcion: "Rompecabezas de 1000 piezas con imagen de paisaje.",
      caracteristicas: ["Material: cartón", "Dimensiones: 70x50 cm", "Incluye poster"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 80
    },
    {
      id: 537,
      nombre: "Juego de Cartas",
      categoria: 5,
      precio: 14.99,
      descripcion: "Juego de cartas para disfrutar con amigos y familia.",
      caracteristicas: ["Número de jugadores: 2-6", "Duración: 30 min", "Edad: 8+"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 120
    },
    {
      id: 538,
      nombre: "Set de Pintura",
      categoria: 5,
      precio: 39.99,
      descripcion: "Set completo de pintura con pinceles y lienzos.",
      caracteristicas: ["Incluye: 12 colores", "Material: acrílico", "Ideal para principiantes"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 539,
      nombre: "Cámara Instantánea",
      categoria: 1,
      precio: 99.99,
      descripcion: "Cámara instantánea para capturar momentos al instante.",
      caracteristicas: ["Formato de foto: 4x6", "Flash incorporado", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 540,
      nombre: "Altavoz Bluetooth",
      categoria: 1,
      precio: 49.99,
      descripcion: "Altavoz Bluetooth portátil con sonido de alta calidad.",
      caracteristicas: ["Batería: 10 horas", "Resistente al agua", "Conexión Bluetooth 5.0"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 80
    },
    {
      id: 541,
      nombre: "Proyector Portátil",
      categoria: 1,
      precio: 299.99,
      descripcion: "Proyector portátil para presentaciones y cine en casa.",
      caracteristicas: ["Resolución: 1080p", "Conexión HDMI", "Batería de 3 horas"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.7,
      destacado: true,
      purchases: 40
    },
    {
      id: 542,
      nombre: "Soporte para Laptop",
      categoria: 1,
      precio: 29.99,
      descripcion: "Soporte ajustable para laptop con ventilación.",
      caracteristicas: ["Material: aluminio", "Ajustable en altura", "Ligero y portátil"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 543,
      nombre: "Funda para Laptop",
      categoria: 1,
      precio: 19.99,
      descripcion: "Funda protectora para laptop de 15 pulgadas.",
      caracteristicas: ["Material: neopreno", "Resistente al agua", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 90
    },
    {
      id: 544,
      nombre: "Cargador Inalámbrico",
      categoria: 1,
      precio: 39.99,
      descripcion: "Cargador inalámbrico rápido para smartphones.",
      caracteristicas: ["Compatible con Qi", "Carga rápida", "Diseño elegante"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 545,
      nombre: "Teclado Mecánico",
      categoria: 1,
      precio: 89.99,
      descripcion: "Teclado mecánico retroiluminado para gamers.",
      caracteristicas: ["Switches: mecánicos", "Retroiluminación RGB", "Diseño ergonómico"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 546,
      nombre: "Mouse Gamer",
      categoria: 1,
      precio: 49.99,
      descripcion: "Mouse gamer con sensor óptico y retroiluminación.",
      caracteristicas: ["DPI ajustable", "Ergonómico", "Conexión USB"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 547,
      nombre: "Monitor 24\"",
      categoria: 1,
      precio: 199.99,
      descripcion: "Monitor Full HD de 24 pulgadas.",
      caracteristicas: ["Resolución: 1920x1080", "Tiempo de respuesta: 5ms", "Conexión HDMI"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 60
    },
    {
      id: 548,
      nombre: "Impresora Multifuncional",
      categoria: 1,
      precio: 129.99,
      descripcion: "Impresora multifuncional con escáner y copiadora.",
      caracteristicas: ["Conexión Wi-Fi", "Impresión a doble cara", "Compatible con móviles"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 50
    },
    {
      id: 549,
      nombre: "Router Wi-Fi",
      categoria: 1,
      precio: 69.99,
      descripcion: "Router Wi-Fi de alta velocidad.",
      caracteristicas: ["Velocidad: 1200 Mbps", "Conexión de 4 puertos", "Fácil configuración"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 80
    },
    {
      id: 550,
      nombre: "Smart TV 55\"",
      categoria: 1,
      precio: 699.99,
      descripcion: "Smart TV de 55 pulgadas con resolución 4K.",
      caracteristicas: ["Resolución: 3840x2160", "Conexión HDMI", "Smart TV"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.7,
      destacado: true,
      purchases: 40
    },
    {
      id: 551,
      nombre: "Altavoz Inteligente",
      categoria: 1,
      precio: 99.99,
      descripcion: "Altavoz inteligente con asistente de voz.",
      caracteristicas: ["Conexión Wi-Fi", "Control por voz", "Sonido de alta calidad"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 552,
      nombre: "Cámara de Acción",
      categoria: 1,
      precio: 149.99,
      descripcion: "Cámara de acción resistente al agua.",
      caracteristicas: ["Resolución: 4K", "Conexión Wi-Fi", "Incluye accesorios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 553,
      nombre: "Gafas de Sol",
      categoria: 2,
      precio: 29.99,
      descripcion: "Gafas de sol con protección UV.",
      caracteristicas: ["Material: plástico", "Colores: varios", "Estilo: moderno"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: false,
      purchases: 100
    },
    {
      id: 554,
      nombre: "Bufanda de Lana",
      categoria: 2,
      precio: 19.99,
      descripcion: "Bufanda de lana suave y cálida.",
      caracteristicas: ["Material: lana", "Tamaño: 180x30 cm", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 555,
      nombre: "Cinturón de Cuero",
      categoria: 2,
      precio: 39.99,
      descripcion: "Cinturón de cuero genuino.",
      caracteristicas: ["Tamaño: ajustable", "Colores: negro, marrón", "Material: cuero"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 556,
      nombre: "Zapatos de Cuero",
      categoria: 2,
      precio: 89.99,
      descripcion: "Zapatos de cuero elegantes para ocasiones especiales.",
      caracteristicas: ["Tallas: 38-45", "Colores: negro, marrón", "Material: cuero"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 557,
      nombre: "Chaqueta de Cuero",
      categoria: 2,
      precio: 149.99,
      descripcion: "Chaqueta de cuero de estilo clásico.",
      caracteristicas: ["Tallas: S-XXL", "Colores: negro, marrón", "Material: cuero"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 50
    },
    {
      id: 558,
      nombre: "Vestido de Verano",
      categoria: 2,
      precio: 49.99,
      descripcion: "Vestido de verano ligero y cómodo.",
      caracteristicas: ["Tallas: S-XL", "Colores: varios", "Material: algodón"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 559,
      nombre: "Pantalones de Mezclilla",
      categoria: 2,
      precio: 59.99,
      descripcion: "Pantalones de mezclilla cómodos y duraderos.",
      caracteristicas: ["Tallas: 28-38", "Colores: azul, negro", "Material: mezclilla"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 560,
      nombre: "Sandalias de Playa",
      categoria: 2,
      precio: 24.99,
      descripcion: "Sandalias de playa cómodas y ligeras.",
      caracteristicas: ["Tallas: 36-45", "Colores: varios", "Material: plástico"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 561,
      nombre: "Bolso de Mano",
      categoria: 2,
      precio: 39.99,
      descripcion: "Bolso de mano elegante y práctico.",
      caracteristicas: ["Material: cuero sintético", "Colores: negro, marrón", "Tamaño: mediano"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 80
    },
    {
      id: 562,
      nombre: "Cartera de Cuero",
      categoria: 2,
      precio: 29.99,
      descripcion: "Cartera de cuero con múltiples compartimentos.",
      caracteristicas: ["Material: cuero", "Colores: negro, marrón", "Tamaño: compacto"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 90
    },
    {
      id: 563,
      nombre: "Gafas de Lectura",
      categoria: 2,
      precio: 19.99,
      descripcion: "Gafas de lectura con diseño moderno.",
      caracteristicas: ["Material: plástico", "Colores: varios", "Tamaño: unisex"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 100
    },
    {
      id: 564,
      nombre: "Sombrero de Paja",
      categoria: 2,
      precio: 24.99,
      descripcion: "Sombrero de paja ideal para el verano.",
      caracteristicas: ["Tamaño: ajustable", "Colores: natural, blanco", "Material: paja"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 80
    },
    {
      id: 565,
      nombre: "Bufanda de Seda",
      categoria: 2,
      precio: 34.99,
      descripcion: "Bufanda de seda suave y elegante.",
      caracteristicas: ["Material: seda", "Tamaño: 180x70 cm", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 566,
      nombre: "Camiseta de Manga Larga",
      categoria: 2,
      precio: 29.99,
      descripcion: "Camiseta de manga larga de algodón.",
      caracteristicas: ["Tallas: S-XXL", "Colores: varios", "Material: algodón"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 567,
      nombre: "Chaqueta de Invierno",
      categoria: 2,
      precio: 99.99,
      descripcion: "Chaqueta de invierno con aislamiento.",
      caracteristicas: ["Tallas: S-XXL", "Colores: negro, azul", "Material: poliéster"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 50
    },
    {
      id: 568,
      nombre: "Pantalones Cortos",
      categoria: 2,
      precio: 24.99,
      descripcion: "Pantalones cortos cómodos para el verano.",
      caracteristicas: ["Tallas: S-XL", "Colores: varios", "Material: algodón"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 569,
      nombre: "Zapatos Deportivos",
      categoria: 2,
      precio: 69.99,
      descripcion: "Zapatos deportivos cómodos y ligeros.",
      caracteristicas: ["Tallas: 36-45", "Colores: varios", "Material: malla"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 570,
      nombre: "Botas de Invierno",
      categoria: 2,
      precio: 89.99,
      descripcion: "Botas de invierno con forro cálido.",
      caracteristicas: ["Tallas: 36-45", "Colores: negro, marrón", "Material: cuero sintético"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 571,
      nombre: "Camiseta de Deporte",
      categoria: 2,
      precio: 19.99,
      descripcion: "Camiseta de deporte ligera y transpirable.",
      caracteristicas: ["Tallas: S-XXL", "Colores: varios", "Material: poliéster"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 100
    },
    {
      id: 572,
      nombre: "Chaqueta de Lluvia",
      categoria: 2,
      precio: 49.99,
      descripcion: "Chaqueta de lluvia impermeable.",
      caracteristicas: ["Tallas: S-XXL", "Colores: negro, azul", "Material: poliéster"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 573,
      nombre: "Pantalones de Chándal",
      categoria: 2,
      precio: 34.99,
      descripcion: "Pantalones de chándal cómodos y ligeros.",
      caracteristicas: ["Tallas: S-XL", "Colores: varios", "Material: algodón"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 574,
      nombre: "Gorra de Beisbol",
      categoria: 2,
      precio: 19.99,
      descripcion: "Gorra de beisbol ajustable.",
      caracteristicas: ["Material: algodón", "Colores: varios", "Tamaño: ajustable"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 575,
      nombre: "Cinturón Deportivo",
      categoria: 2,
      precio: 24.99,
      descripcion: "Cinturón deportivo ajustable.",
      caracteristicas: ["Material: nylon", "Colores: varios", "Tamaño: ajustable"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 80
    },
    {
      id: 576,
      nombre: "Mochila de Senderismo",
      categoria: 2,
      precio: 59.99,
      descripcion: "Mochila de senderismo resistente y ligera.",
      caracteristicas: ["Capacidad: 30L", "Material: poliéster", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 577,
      nombre: "Botella Térmica",
      categoria: 2,
      precio: 29.99,
      descripcion: "Botella térmica de acero inoxidable.",
      caracteristicas: ["Capacidad: 500ml", "Mantiene la temperatura", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 578,
      nombre: "Cámara de Seguridad",
      categoria: 1,
      precio: 89.99,
      descripcion: "Cámara de seguridad para interiores y exteriores.",
      caracteristicas: ["Visión nocturna", "Conexión Wi-Fi", "Detección de movimiento"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 60
    },
    {
      id: 579,
      nombre: "Cargador Solar",
      categoria: 1,
      precio: 49.99,
      descripcion: "Cargador solar portátil para dispositivos móviles.",
      caracteristicas: ["Capacidad: 10000mAh", "Resistente al agua", "Compatible con todos los smartphones"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 70
    },
    {
      id: 580,
      nombre: "Cafetera Eléctrica",
      categoria: 3,
      precio: 79.99,
      descripcion: "Cafetera eléctrica con función de programación.",
      caracteristicas: ["Capacidad: 12 tazas", "Placa caliente", "Filtro reutilizable"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 60
    },
    {
      id: 581,
      nombre: "Silla de Oficina",
      categoria: 3,
      precio: 149.99,
      descripcion: "Silla ergonómica para oficina con soporte lumbar.",
      caracteristicas: ["Ajustable en altura", "Ruedas giratorias", "Material: malla"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 40
    },
    {
      id: 582,
      nombre: "Juego de Sábanas",
      categoria: 3,
      precio: 39.99,
      descripcion: "Juego de sábanas de microfibra suave y duradero.",
      caracteristicas: ["Tamaños: individual, matrimonial", "Colores: varios", "Fácil de lavar"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: false,
      purchases: 80
    },
    {
      id: 583,
      nombre: "Cama King Size",
      categoria: 3,
      precio: 899.99,
      descripcion: "Cama king size con colchón de espuma.",
      caracteristicas: ["Material: madera", "Colores: blanco, marrón", "Dimensiones: 200x200 cm"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.7,
      destacado: true,
      purchases: 30
    },
    {
      id: 584,
      nombre: "Espejo de Pared",
      categoria: 3,
      precio: 59.99,
      descripcion: "Espejo de pared con marco decorativo.",
      caracteristicas: ["Tamaño: 80x60 cm", "Material: vidrio", "Colores: varios"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 50
    },
    {
      id: 585,
      nombre: "Lámpara de Mesa",
      categoria: 3,
      precio: 29.99,
      descripcion: "Lámpara de mesa con luz LED regulable.",
      caracteristicas: ["Material: plástico", "Colores: blanco, negro", "Altura: 30 cm"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.4,
      destacado: true,
      purchases: 80
    },
    {
      id: 586,
      nombre: "Cojín Decorativo",
      categoria: 3,
      precio: 19.99,
      descripcion: "Cojín decorativo para el sofá.",
      caracteristicas: ["Material: poliéster", "Colores: varios", "Tamaño: 45x45 cm"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: false,
      purchases: 100
    },
    {
      id: 587,
      nombre: "Candelabro de Metal",
      categoria: 3,
      precio: 24.99,
      descripcion: "Candelabro de metal para velas.",
      caracteristicas: ["Material: metal", "Colores: dorado, plateado", "Tamaño: 20 cm"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 588,
      nombre: "Cesta de Almacenamiento",
      categoria: 3,
      precio: 34.99,
      descripcion: "Cesta de almacenamiento de mimbre.",
      caracteristicas: ["Material: mimbre", "Tamaño: 30x30x30 cm", "Colores: natural, blanco"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 589,
      nombre: "Reloj de Pared",
      categoria: 3,
      precio: 39.99,
      descripcion: "Reloj de pared con diseño moderno.",
      caracteristicas: ["Material: plástico", "Colores: varios", "Tamaño: 30 cm"],
      imagen: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ninja-kamui-con-oni-mascarilla_3840x2160_xtrafondos.com-6FV5y150Eky0156rvmcBPp9ePs83g4.jpg",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 590,
      nombre: "Pantalon Cargo Azul",
      categoria: 3,
      precio: 
      50.500,
      descripcion: "CPantalon Cargo Azul Mom Jean Matizado Premium Hombre",
      caracteristicas: ["azul",
        "talla: 42"
      ],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_623447-MLA77788802121_072024-O.webp",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 599,
      nombre: "Motorola Moto",
      categoria: 3,
      precio: 799.999,
      descripcion: "Motorola Moto G85 5g 256Gb + 8GB Ram Urban Grey",
      caracteristicas: ["Peso: 200g", "Ideal para perros", "Sabor: pollo"],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_846793-MLU78368590992_082024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 600,
      nombre: "Tarjeta De Video",
      categoria: 3,
      precio: 421.999,
      descripcion: "Tarjeta De Video Msi Geforce Rtx 3050 Gaming X 6g",
      caracteristicas: [
        "Tamaño de la memoria: 6 GB",
        "Interfaz PCI-Express 4.0.",
        "Bus de memoria: 128bit.",
      ],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_988926-MLU75482979777_032024-O.webp",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 601,
      nombre: "Tarjeta gráfica",
      categoria: 3,
      precio: 383.999,
      descripcion: "Tarjeta gráfica Msi Geforce Rtx 3050 Gaming X 6gb Gddr6 96bit",
      caracteristicas: [
        "Tamaño de la memoria: 6 GB",
        "Interfaz PCI-Express 4.0.",
        "Interfaz de memoria: 92 bits.",
        "Dispone de una conexión: HDMI",
      ],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_842879-MLU77148112435_062024-O.webp",
      calificacion: 4.6,
      destacado: true,
      purchases: 70
    },
    {
      id: 602,
      nombre: "Pc Diseño Grafico",
      categoria: 3,
      precio: 99.349,
      descripcion: "Pc Diseño Grafico I5 12th Ram 32gb Ssd 1tb Rtx 3050 6gb Wifi",
      caracteristicas: [],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_603178-MLA80197665713_102024-O.webp",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 603,
      nombre: "Pc Gamer ",
      categoria: 3,
      precio: 692.999,
      descripcion: "Pc Gamer Armada Ryzen 7 5700g Ram 32b Disco Ssd 1tb Wifi W10",
      caracteristicas: [],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_653794-MLA79440145658_102024-O.webp",
      calificacion: 3,
            destacado: true,
      purchases: 70
    },
    {
      id: 604,
      nombre: "Pc Gamer Ryzen",
      categoria: 3,
      precio: 9.99,
      descripcion: "Pc Gamer Ryzen 7 5700g Ram 32gb Vega 8 960gb Wifi",
      caracteristicas: [],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_649332-MLA76740809050_062024-O.webp",
      calificacion: 4.5,
      destacado: true,
      purchases: 80
    },
    {
      id: 604,
      nombre: "Pc Armada Gamer Ryzen 7", 
      categoria: 1, 
      precio:712.500,
      descripcion: "Pc Armada Gamer Ryzen 7 5700g 32gb Vega 8 960gb Wifi",
      caracteristicas: ["RYZEN 7 5700G",
        "1 TB",
        "AMD",
        "Ryzen 7",
        "5700G",
        "32 GB",
      ],
      imagen: "https://http2.mlstatic.com/D_NQ_NP_839757-MLA78694238162_092024-O.webp" ,
      calificacion: 4.5,
      destacado: true,
      purchases: 80,
      mercado: "Producto muy popular entre los dueños de gatos. La mayoría de los juguetes de peluche para gatos incluyen sonidos o texturas que estimulan el juego. Este producto se destaca por su diseño colorido y duradero."
  }
  ];


export default productosData

